---
- hostname: localhost
  environment: DEV
  system: SystemWithSimpleStatusCheck
- hostname: localhost
  environment: PROD
  system: SystemWithSimpleStatusCheck
- hostname: 127.0.0.1
  environment: PROD
  system: SystemWithSimpleStatusCheck
- hostname: localhost
  environment: PROD
  system: SystemWith404
- hostname: localhost
  environment: DEV
  system: SystemMissingColor
- hostname: localhost
  environment: DEV
  system: SystemStatusYellow
- hostname: 127.0.0.1
  environment: DEV
  system: SystemStatusYellow
- hostname: localhost
  environment: DEV
  system: ComponentsOnly
- hostname: localhost
  environment: DEV
  system: ComplexSystemStatus
- hostname: localhost
  environment: UAT
  system: ComponentStatuses
- hostname: localhost
  environment: UAT
  system: 4SecTimeout
- hostname: localhost
  environment: UAT
  system: 5SecTimeout
- hostname: localhost
  environment: UAT
  system: redirect
